/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as WithdrawScriptJson } from "../withdraw.ral.json";

export namespace Withdraw {
  export async function execute(
    signer: SignerProvider,
    params: ExecuteScriptParams<{ token: HexString; amount: bigint }>
  ): Promise<ExecuteScriptResult> {
    const signerParams = await script.txParamsForExecution(signer, params);
    return await signer.signAndSubmitExecuteScriptTx(signerParams);
  }

  export const script = Script.fromJson(WithdrawScriptJson);
}
