import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import { connectWallet, silentConnectWallet } from '@/services/wallet.service'
import { TokenDapp } from '@/components/TokenDapp'
import { groupOfAddress } from '@alephium/web3'

export default function Home() {
  const [address, setAddress] = useState<string>()
  const [network, setNetwork] = useState<string | undefined>(undefined)
  const [isConnected, setConnected] = useState(false)

  useEffect(() => {
    const handler = async () => {
      const wallet = await silentConnectWallet(
        () => {
          return Promise.resolve(setConnected(false))
        }
      )
      setAddress(wallet?.connectedAddress)
      setNetwork(wallet?.connectedNetworkId)
      setConnected(!!wallet?.connectedNetworkId)
    }

      ; (async () => {
        await handler()
      })()

    return () => {
    }
  }, [])

  const handleConnectClick = async () => {
    const wallet = await connectWallet(
      () => {
        return Promise.resolve(setConnected(false))
      }
    )
    setAddress(wallet?.connectedAddress)
    setNetwork(wallet?.connectedNetworkId)
    setConnected(!!wallet?.connectedNetworkId)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Token Faucet</title>
        <meta name="description" content="Generated by @alephium/cli init" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {(isConnected && address) ? (
        <>
          <h3 style={{ margin: 0 }}>
            Wallet address: <code>{address} (Group {groupOfAddress(address)})</code>
          </h3>
          {address && (
            <TokenDapp address={address} network={network} />
          )}
        </>
      ) : (
        <>
          <button className={styles.connect} onClick={handleConnectClick}>
            Connect Wallet
          </button>
          <p>First connect wallet to use dapp.</p>
        </>
      )}

    </div>
  )
}
